USERS = {'My user': {'product1': 2,
             'product10': 2,
             'product2': 0,
             'product3': 1,
             'product4': 0,
             'product5': 0,
             'product6': 0,
             'product7': 2,
             'product8': 1,
             'product9': 1},
 'user1': {'product1': 0,
           'product10': 0,
           'product2': 1,
           'product3': 0,
           'product4': 2,
           'product5': 2,
           'product6': 1,
           'product7': 2,
           'product8': 0,
           'product9': 2},
 'user2': {'product1': 2,
           'product10': 2,
           'product2': 1,
           'product3': 0,
           'product4': 1,
           'product5': 1,
           'product6': 0,
           'product7': 2,
           'product8': 2,
           'product9': 1},
 'user3': {'product1': 0,
           'product10': 2,
           'product2': 1,
           'product3': 1,
           'product4': 0,
           'product5': 1,
           'product6': 0,
           'product7': 1,
           'product8': 2,
           'product9': 1},
 'user4': {'product1': 2,
           'product10': 0,
           'product2': 0,
           'product3': 1,
           'product4': 1,
           'product5': 2,
           'product6': 0,
           'product7': 2,
           'product8': 1,
           'product9': 1},
 'user5': {'product1': 0,
           'product10': 1,
           'product2': 2,
           'product3': 0,
           'product4': 2,
           'product5': 1,
           'product6': 0,
           'product7': 1,
           'product8': 2,
           'product9': 1}}
